### ISSUE TITLE
Blog Post: Migrating Force/Microgravity to OSS by Default

### ISSUE THREAD

**Issue by orta** [artsy/mobile#102]
Should note upfront that it's not my story, but that I helped out, as a part of [my Artsy Trello](https://trello.com/c/ng79qsJh/31-move-all-product-development-to-oss-by-default)

- [ ] The issues https://github.com/artsy/microgravity-private/issues/1468 and https://github.com/artsy/force-private/issues/5451
- [ ] Setting up CI
- [ ] work-arounds for ENV vars
- [ ] Deployment
- [ ] Issue migration
- [ ] Show the "force dance" - https://artsy.slack.com/files/roop/F228NGEA2/force-dance.sh

Wrap up with a discussion on whether this means the web is now also at OSS by Default too now? 

Microgravity - https://artsy.slack.com/archives/web/p1472228416000972
Force - https://artsy.slack.com/archives/web/p1471369222000673

**Comment by ashfurrow** [comment]
I think this is done, right?

**Comment by orta** [comment]
Yes!
