### ISSUE TITLE
Eigen 2.0.0 event

### ISSUE THREAD

**Issue by orta** [artsy/mobile#12]
We should do beers, or lunch, or something.

**Comment by orta** [comment]
Hrmmmmmm, we should do something, as it was launched today.

**Comment by ashfurrow** [comment]
:tada:

**Comment by katarinabatina** [comment]
wooo! I feel bad celebrating w/o @1aurabrown and @alloy we should do digital champagne standup

**Comment by alloy** [comment]
That sounds excellent, does it involve real :cocktail:?

**Comment by orta** [comment]
haha, I'm calling this a missed one :dancers:
