### ISSUE TITLE
Folio 2.0.0 Event

### ISSUE THREAD

**Issue by orta** [artsy/mobile#13]
We should do beers / lunch / something

**Comment by orta** [comment]
We could do an [Escape The Room](http://static.escapetheroomnyc.com/downtown.html), when Danger & Ash are over?

**Comment by ashfurrow** [comment]
Looks cool!

**Comment by ArtsyBecca** [comment]
I'm so in! I've really wanted to do one of those. 
There's also Trapped in a Room with a Zombie http://roomescapeadventures.com/
Any time but March 1-8 works for me!

**Comment by orta** [comment]
OK let's do March the 9th at 8 o'clock. Is this good for everyone?

**Comment by ashfurrow** [comment]
This works for me!

**Comment by orta** [comment]
@katarinabatina - are you in for this?

**Comment by ArtsyBecca** [comment]
March 9 works for me too!

**Comment by katarinabatina** [comment]
I will be out of town but you guys go for it!

**Comment by orta** [comment]
OK, can't book for 7 people at 8pm, can do for 10:30pm though. 
Going to book this in 2 hours, if you _cannot_ do this time, now is a good time to speak up.

**Comment by orta** [comment]
Booked: 
```
107 Suffolk Street 2nd Floor, New York, New York 10002 
Phone : 347-954-9160 

Monday, March 9, 2015
Time:	10:30 PM - 11:30 PM   (1 hour)
```

![screen shot 2015-03-04 at 20 21 27](https://cloud.githubusercontent.com/assets/49038/6497331/15efc7c4-c2ac-11e4-8334-e0379b9396d3.png)

That's, _Orta, Danger, Laura, Becca, Ash, Ashley & Sarah_. 

Given it's late-ness, it might make sense to do [dinner/drinks](https://github.com/orta/house/issues/7) [around the area](https://www.google.com/maps?q=107+Suffolk+Street+2nd+Floor,+New+York,+New+York+10002). Any ideas?

**Comment by orta** [comment]
OK, what about 7:30 dinner at [Katja](http://www.cafekatja.com)? Went there a few weeks ago for sunday lunch, was awesome. There's a the [Cake Shop](http://cake-shop.com) nearby which we can grab dessert + cake from until it starts. Should fly by.

**Comment by AshleyKrista** [comment]
Sounds amazing

**Comment by orta** [comment]
to-done. 

Good work escaping.

**Comment by orta** [comment]
![10405526_748903221892408_3045314776716893105_n](https://cloud.githubusercontent.com/assets/49038/6653274/56261246-ca61-11e4-9c56-04989ae2242c.jpg)
