### ISSUE TITLE
Deal with CI issues

### ISSUE THREAD

**Issue by orta** [artsy/mobile#17]
Options:
* TeamCity - https://twitter.com/orta/status/568788102745079808
  * - https://github.com/foreflight/foreflight_build_agent

**Comment by ashfurrow** [comment]
If we could use something that allowed us to use pre-release versions of Xcode, that would help me with Eidolon wrt Swift improvements.

**Comment by orta** [comment]
http://staxmanade.com/2015/01/setting-jenkins-up-to-run-xctool-and-xcode-simulator-tests/

**Comment by ashfurrow** [comment]
Should we close this? Seems like we've settled on Travis/Circle.

**Comment by orta** [comment]
yeah, I'm not going iOSDevOps.
