### ISSUE TITLE
Scheduling time on a Mobile Team Calendar 

### ISSUE THREAD

**Issue by katarinabatina** [artsy/mobile#23]
Hi all,

Given that @alloy works remotely, @1aurabrown is in and out due to jury duty, and both @ashfurrow and @orta are devoted speakers on behalf of the team, it would be great if we could start to schedule things more "visually" so me and the rest of the team have more of an idea when people are online and available versus working on a talk, out of town for a talk, workin' on the house boat, etc. Scheduling things in advance will also help us to understand how much we can get done on a particular sprint. 

Using the team OOO calendar should also be something we feel free to use but Orta suggested that a specific mobile team calendar may be helpful. Thoughts?

**Comment by orta** [comment]
I turn off the Out of Office calendar every time, given that artsy is 100+ people the notifications are useless and it takes up useful space on a calendar app. 

I'd imagine the mobile one as a better version of if we all had repos like my travel one: https://github.com/orta/travel - allowing for finer grained long-views of what everyone is up to for a month.

**Comment by alloy** [comment]
Yeah a team specific calendar sounds like a good idea and I’d also like to have one to have a better idea of when/who is available.

**Comment by ashfurrow** [comment]
:+1:

**Comment by orta** [comment]
Done: https://www.google.com/calendar/embed?src=artsymail.com_bke4sctkn8o072rjgtcsrrun3s%40group.calendar.google.com&ctz=America/New_York

Everyone should be able to make edits, I moved a lot of my `orta@artsymail.com` events over. Could do the same for standup etc too?
