### ISSUE TITLE
Experiment with Pod-based View Controllers

### ISSUE THREAD

**Issue by orta** [artsy/mobile#30]
If we wanted to move a View Controller from Eigen, or to offer limited versions in one app but not another we would need a way to separate out the dependency graph. 

* What does this look like?
* How should they react?
* How can then interact with other Pod-like VCs?
* What about additional contexts?
* Model objects as protocols?

Assigned to @ashfurrow for investigation

**Comment by orta** [comment]
Expanded out of https://github.com/artsy/mobile/issues/22

**Comment by orta** [comment]
https://github.com/artsy/mobile/issues/28 does a much better job of this issue.

**Comment by ashfurrow** [comment]
Haha, totally missed this whoops.
