### ISSUE TITLE
Create a tool that fails CI based on the PR itself

### ISSUE THREAD

**Issue by orta** [artsy/mobile#31]
So, you'd write a DSL which is given a few ivars e.g: ` lines_of_code`, `pr_url`, `number_of_commits`, `files_modified`, `files_added`, `files_removed`

Culturefile:
```
if (lines_of_code > 20) && (files_modified.includes? "CHANGELING.yml" == false) {
    fail "needs to have a changelog note for large changes"
}

if (files_added.length > 2) && (files_modified.includes? "ARAppDelegate+Analytics" == false)  {
    warn "You may want analytics"
}
```

**Comment by neonichu** [comment]
CHANGELING.yml :heart_eyes_cat:

**Comment by orta** [comment]
best kinds of YANIMALS

**Comment by getaaron** [comment]
Should `<` be `>`?

**Comment by orta** [comment]
I don't really care about the actual code in there, it's just pseudo code to demonstrate the potential idea.

**Comment by orta** [comment]
This can be grabbed now in:
  * travis: via the ENV vars: `TRAVIS_REPO_SLUG` and `TRAVIS_PULL_REQUEST` 
  * circle: via `CI_PULL_REQUEST` which is the full URL

**Comment by orta** [comment]
Talked it over with Danger, she thinks it should be called Columbo, and be that "one more thing"  thing, [with one of these GIFs](http://legomessageboards.wikia.com/wiki/User_blog:AmazingPythor/Useful_Columbo_GIFs). Given that there's already a ruby gem called columbo, I'll use brew and write in swift. Only wish there was a dependency manager that could do swift command line tools.

**Comment by ashfurrow** [comment]
Nice – good idea! I'd suggest running it early in the CI process so that it fails quickly. 

![](http://33.media.tumblr.com/a924e830d632d5e3a197c49c8173dcc9/tumblr_inline_nebkgmJwxg1qju3o3.gif)

**Comment by orta** [comment]
Would be nice to mix with https://github.com/blog/2051-protected-branches-and-required-status-checks

**Comment by orta** [comment]
This has started development at https://github.com/orta/danger

**Comment by ashfurrow** [comment]
![](https://media0.giphy.com/media/bZCdWtwbcXUcM/200.gif)

**Comment by orta** [comment]
Related: http://techlife.cookpad.com/entry/2015/06/04/dokumi-en

**Comment by orta** [comment]
This is definitely good enough. Long live danger.
