### ISSUE TITLE
Application(s) strategy

### ISSUE THREAD

**Issue by alloy** [artsy/mobile#35]
@artsy/mobile 

After talking with @orta and @katarinabatina over the past months, it’s becoming more and more clear to  me that the current approach of trying to essentially replicate the Artsy platform in a native application doesn’t scale very well.

We’re often just playing catch-up with changes on the web apps and because we’re dealing with native code, these changes often take more time to implement than on the web. This means that there’s little time to actually work on awesome features for our users that would _only be possible in a native app_.

Besides that is also the issue that the web app can be updated and deployed immediately, whereas the native app has to deal with the App Store review time, making this an even more painful experience.

-----

My suggestion is the following:

* We create a completely new Eigen app that is a very lean application:
  - it basically shows martsy views for _all_ of its content
  - only features that benefit from native integration are implemented natively, e.g.:
    * bottom tab bar
    * navigation stack and transition animations
    * sharing content (social, email, text message, etc)
    * search controller
    * push notification handling
    * VIR, although I think this should be very doable in HTML/CSS and thus also be available on martsy
  - we use state-of-the-art WebKit APIs to integrate the web and native components. E.g. on iOS we should now have access to all the WebKit APIs and so we should be able to advanced DOM integration work.
* We port that new Eigen app to Android, which should be much less work to do initially and to maintain.
* martsy might need to be more optimised to work on mobile devices of more sizes, e.g. iPad, because force’s browser paradigm often doesn’t feel right when embedded into a native app imo. (E.g. the extra navigation bars that some pages have, such as those of a fair.)

Pros:

* Most design changes and/or content fixes will be available immediately as they are deployed to the web.
* When we start localising content, we only need to do that in one place, namely on the web (which benefits all users). Any content that needs to be localised in the apps will be very minimal.
* No need to duplicate other efforts, such as analytics.
* We have spare time :cocktail: :tada: to spend on smaller targeted truly native apps that target iOS and Android, possibly implemented in something like React Native, for e.g. fair specific apps, collector apps, etc, as @katarinabatina and @orta were already discussing.

Cons:

* Native feel may decline, but as our UI already doesn’t have that pure iOS native feel, I think this can be kept to a minimum.
  - I do think that our mobile expertise should be taken into account when designing/implementing the martsy views, to ensure those behave as native as possible.
  - I think it would make sense to invest in a CSS3 expert that would be able to give a native-like (e.g. animated) feel to the UI. Or do we already have someone for that?
* A lot of ‘wasted’ effort on the existing code-base. That’s an emotional issue, which I can totally sympathise with 😓

**Comment by alloy** [comment]
If this sounds like an option, I would like to devote some time this sprint to play with WKWebView to see what it’s possibilities for this would be and create a simple prototype.

**Comment by katarinabatina** [comment]
Hi @alloy, thanks for the thorough look into the possibilities here. 

While the pros seem valid in this strategy the ultimate con is giving our 200,000+ mobile users a downgraded experience. On that note, I am fairly confident that what we imagine for a collector-focused app is much closer to what we have in eigen now and therefore I am far more interested in in migrating current eigen in that direction. The fear is loosing our collector audience who are already using eigen to power their collecting experiences. 

I would hope, as you mentioned that eigen as a collecting app would cease to chase the web but instead work towards building a fully native experiences. Let's chat more today if you have time.

**Comment by ashfurrow** [comment]
Yeah, I'm of two minds on this. @alloy does a great job of listing the pros and cons that concern me, and @katarina raises an excellent point. I think this underscores the importance of chatting about the direction of our apps in general. For example, porting to Android is important, but what will that app look like? Would it be eigen as it is today or eigen for collectors? 

Exciting times!

**Comment by katarinabatina** [comment]
I would say Android is important for sure but I feel less strongly about putting efforts towards it until we've really delivered on a strong mobile strategy in iOS

**Comment by alloy** [comment]
> the ultimate con is giving our 200,000+ mobile users a downgraded experience

Definitely agreed.

**Comment by orta** [comment]
> On that note, I am fairly confident that what we imagine for a collector-focused app is much closer to what we have in eigen now and therefore I am far more interested in in migrating current eigen in that direction. The fear is loosing our collector audience who are already using eigen to power their collecting experiences.

This feels weird to me, are you thinking of transitioning the current eigen app to this? It's focus has been on exploring the art world, and I'd be really put off if I wasn't a collector and suddenly the app had pivoted to mainly buying art.

**Comment by katarinabatina** [comment]
@orta it is a tough choice but it's important from a business standpoint that we capture our collector base already on the app.

**Comment by orta** [comment]
We talked this though, and we're in agreement on the direction :dancers:

**Comment by alloy** [comment]
:+1:
