### ISSUE TITLE
Blog about open source library selection process

### ISSUE THREAD

**Issue by dskatz22** [artsy/mobile#46]
What considerations are made, test coverage, community support, pretty README, code quality etc.

**Comment by orta** [comment]
Interesting, given that I created the CocoaPods quality indexes, [they contain the sum of what I believe](https://guides.cocoapods.org/making/quality-indexes.html), but I'd be open for someone else to take a look at this.

**Comment by ashfurrow** [comment]
As a product of working with Orta, my criteria match his closely.

I'm fairly liberal in adding dependencies – I'd much rather use something someone else has written for a variety of reasons. Maybe those reasons would make a good post?

**Comment by orta** [comment]
We expanded a bit of that on our objc.io

> There is a tendency, particularly in iOS developer communities, to eschew third-party dependencies. Developers fall victim to “Not Invented Here” syndrome and end up wasting valuable hours of development time tackling the same problems others have already solved for them. On our mobile team, we vehemently reject NIH syndrome and instead favor the philosophy of “Proudly Discovered Elsewhere” (a phrase we appropriated from another developer, naturally).

Good examples where we had space to do NIH: NAMapView, FBSnapshots & Expecta/Specta.

**Comment by orta** [comment]
Linked to #49

**Comment by orta** [comment]
I did this!
