### ISSUE TITLE
Blog Post: Cocoa Architecture: Dependencies

### ISSUE THREAD

**Issue by orta** [artsy/mobile#49]
I know that we went into it at "Artsy Mobile's Culture" but that doesn't go into bundler, fastlane, pods etc etc.

**Comment by orta** [comment]
Started my outlining - https://github.com/artsy/artsy.github.io/compare/source...deps_blog

**Comment by ashfurrow** [comment]
Fixed by https://github.com/artsy/artsy.github.io/pull/161
