### ISSUE TITLE
Blog Post: MVVM for greater refactorings

### ISSUE THREAD

**Issue by orta** [artsy/mobile#53]

**Comment by ashfurrow** [comment]
@sarahscott I know you've been working on MVVM on Energy, and I just [moved](https://github.com/artsy/eidolon/pull/503) our biggest view controller in Eidolon to MVVM. I think it would be super-cool to collaborate on a pair of blog posts, from each of our perspectives. Having someone new to MVVM discuss the pros/cons/challenges would be _so cool_, and I think there's also an opportunity to discuss transitioning a very complex view controller into MVVM from a Swift/FRP perspective.

**Comment by ashfurrow** [comment]
I've got a _very rough_ draft up here: https://gist.github.com/ashfurrow/655fc2daac4433d8b03a

Looking for more visuals to help explain concepts. Feedback welcome :tea:

**Comment by orta** [comment]
@sarahscott any word on this post?

**Comment by alloy** [comment]
Seeing as we already have #162, I’m closing this.
