### ISSUE TITLE
Blog Post: Advice for Juniors

### ISSUE THREAD

**Issue by orta** [artsy/mobile#57]
Something that can build off Dave's - https://github.com/dbgrandi/dbgrandi.github.io/pull/8

I've been giving a bunch of talks to hack schools with a lot of low-level pragmatic advice around both contributing to OSS and getting your first job and doing well in it. Can build off that.

**Comment by orta** [comment]
Use Mike as a good example: https://github.com/FullMetalFist

**Comment by orta** [comment]
Stephan of ShopKeep recommended raising people up to dev positions from QA etc, definitely worth a paragraph or two.

**Comment by orta** [comment]
I wonder if this could be the next thing after the interviewing one. I'll let this settle in my head for a while.

**Comment by orta** [comment]
I think this is fine for the topic - https://github.com/artsy/artsy.github.io/pull/275

**Comment by jcampbell05** [comment]
@orta  would love a blog on how to grow into senior role :)

**Comment by orta** [comment]
That's what I just linked to in that closing comment ^

**Comment by orta** [comment]
Or do you want engineering 2 -> 3?

**Comment by jcampbell05** [comment]
Engineering 2 -> 3 ?  But that looks great :)
