### ISSUE TITLE
Eidolon Rx Video

### ISSUE THREAD

**Issue by ashfurrow** [artsy/mobile#66]
Similar to Orta's emergence walk-through, I should discuss changes to Eidolon with our Rx switch.

**Comment by ashfurrow** [comment]
I'm tackling this at Thursday's Lunch&Learn.

**Comment by orta** [comment]
Thing that I did for the first lunch & learn, get the webcam and set it up to look at you and the big screen. Use Screenflow to record both your screen + you externally at once. Using one of those usb mics works well enough for audio. You're not gonna be shipping it to treehouse but people don't expect that level of production value.

Then try craft some narrative, "Jane Brown wants to make a bid" what is the underlying process that makes that happen, from first tapping the screen to look through a sale to placing a bid. Jumping between the story, the storyboard and the code can probably work out well.

**Comment by ashfurrow** [comment]
So I don't want to go over time tomorrow, so I want to focus on a few of the following things:

- Overview of what the app is, does, and is for
- XApp tokens and networking
- Division between listings & bid fulfillment storyboards (incl using sbconstants)
- Listings view controller & view model pair (all the complex logic is in the view model, but I want to focus only on the controller)
- `PlaceBidNetworkModel` is my favourite :heart_eyes_cat: I want to talk about how it's tested, and also how the protocol it conforms to is used by the loading view model as a dependency and its tests
- Loading view model is super interesting, how it delegates out to other models (see above)

I think that should be good. I don't really want to go into the theory of FRP, so doing the XApp stuff early will be good to show how its used instead of explaining. With a few exceptions, everything else in the app is described by one of the cases I do cover.

I'll make sure as I'm describing each component to contextualize it as a part of a narrative, ex: 'the user is shown the loading view controller while their bid is being placed, it does X Y and Z, let's look at Y.'

**Comment by ashfurrow** [comment]
Done :tada:
