### ISSUE TITLE
Laura has to write a blog post

### ISSUE THREAD

**Issue by orta** [artsy/mobile#7]
dooooooooo ittttttttttt

This is a happiness enhancement for me.

**Comment by ashfurrow** [comment]
Is this accomplished via our objc.io post?

**Comment by orta** [comment]
Not sure, how do you feel about that @1aurabrown?

**Comment by ashfurrow** [comment]
We can open a new issue: "Laura needs to write _another_ blog post" :P

**Comment by orta** [comment]
Well, at least you got an objc.io and a post announcing it on our blog too :dancers:
